#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/SimpleTracker.Api/ && \
    dotnet build src/SimpleTracker.Api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/SimpleTracker.Api/SimpleTracker.Api.csproj --launch-profile web"
