name: simple-tracker-dotnet-api smoke test

on: 
  workflow_dispatch:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  newman:
   uses: boxboat-github-practice/reusable-workflows/.github/workflows/simple-tracker-test.yaml@main
   with:
    port: 8080
